spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:
        url: jdbc:mysql://127.0.0.1:3307/zx-mall?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    profiles:
        active: dev

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-value: 1
            logic-not-delete-value: 0
    mapper-locations:
        - classpath*:/mapper/*.xml
